In [2]:
import torch

torch.arange(0, 8, 2)

tensor([0, 2, 4, 6])

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([5, 6, 7, 8, 9])

print(a.unsqueeze(0).shape, b.shape)

# print(b.T @ a)

a.sin(), b.cos()

torch.Size([1, 3]) torch.Size([5])


(tensor([0.8415, 0.9093, 0.1411]),
 tensor([ 0.2837,  0.9602,  0.7539, -0.1455, -0.9111]))

In [4]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

b = torch.tensor([10, 100, 1000])

b * a

tensor([[  10,  200, 3000],
        [  40,  500, 6000]])

In [5]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# a.repeat_interleave()
# torch.repeat_interleave()

In [6]:
y = torch.tensor([[1, 2], [3, 4]])
# 对二维张量来说，如果不设置 dim，
# 那么 torch.repeat_interleave 会先把它“展平成一维”，
# 然后再按元素重复，最后返回一维结果。
torch.repeat_interleave(y, 2)

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [7]:
a = {}

b = {"x": 1}

len(a), len(b)

(0, 1)

In [12]:
x = torch.tensor([True, False, True])

x.nonzero(as_tuple=True)

(tensor([0, 2]),)

In [13]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

x[[1, 2]]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [12]:
[1, 2, 3] == [1, 2, 3]

x = []
y = [1, 2, 3]

# assert not x
# assert not y

print(bool(x), bool(y))

False True


In [15]:
for i in [1, 2, 3]:
    if i == 2:
        continue
    print(i)

1
3


In [4]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
(a, *_) = x
a

1

In [4]:
for i in range(1):
    print(i)

0


In [7]:
from collections import deque

x = deque()
x.append(1)
x.append(2)
x.append(1)

print(x)

x.remove(1)

print(x)

x.remove(1)

print(x)


deque([1, 2, 1])
deque([2, 1])
deque([2])


In [10]:
import xxhash

x = 0
h = xxhash.xxh64()
h.update(x.to_bytes(8))
h.intdigest()

3803688792395291579

In [7]:
x = 1

while x > 5:
    print(x)
    break
else:
    print("====")
    x += 1

====


In [10]:
from collections import deque

x = [1, 2, 3]
y = deque([7, 8, 9])

y.extendleft(x)

y


deque([3, 2, 1, 7, 8, 9])

In [20]:
x = {1: 2, 3: 4}

y = {1: 100, 0: 6}

x.update(y)

print(x, y)

sorted(x)

len(x)

{1: 100, 3: 4, 0: 6} {1: 100, 0: 6}


3

In [21]:
list(range(16, 10, 16))

[]