In [8]:
import torch

torch.arange(0, 8, 2)

tensor([0, 2, 4, 6])

In [19]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([5, 6, 7, 8, 9])

print(a.unsqueeze(0).shape, b.shape)

# print(b.T @ a)

a.sin(), b.cos()

torch.Size([1, 3]) torch.Size([5])


(tensor([0.8415, 0.9093, 0.1411]),
 tensor([ 0.2837,  0.9602,  0.7539, -0.1455, -0.9111]))

In [34]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

b = torch.tensor([10, 100, 1000])

b * a

tensor([[  10,  200, 3000],
        [  40,  500, 6000]])