In [2]:
import torch

torch.arange(0, 8, 2)

tensor([0, 2, 4, 6])

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([5, 6, 7, 8, 9])

print(a.unsqueeze(0).shape, b.shape)

# print(b.T @ a)

a.sin(), b.cos()

torch.Size([1, 3]) torch.Size([5])


(tensor([0.8415, 0.9093, 0.1411]),
 tensor([ 0.2837,  0.9602,  0.7539, -0.1455, -0.9111]))

In [4]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

b = torch.tensor([10, 100, 1000])

b * a

tensor([[  10,  200, 3000],
        [  40,  500, 6000]])

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# a.repeat_interleave()
# torch.repeat_interleave()

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
y = torch.tensor([[1, 2], [3, 4]])
# 对二维张量来说，如果不设置 dim，
# 那么 torch.repeat_interleave 会先把它“展平成一维”，
# 然后再按元素重复，最后返回一维结果。
torch.repeat_interleave(y, 2)

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [1]:
a = {}

b = {"x": 1}

len(a), len(b)

(0, 1)